### ISSUE TITLE
Imena stolpcev in tabele pri vizualizaciji

### ISSUE THREAD

**Issue by timotejvesel** [nezakrzan/APPR-2020-21#1]
Opazil sem, da imaš v nekaterih imenih stolpcev presledek (npr. stolpec `gospodarska dejavnost` v tabeli `gospodarskadejavnost`). Bolje bo, da se presledkom izogibaš in jih nadomestiš s piko.

Priporočam še, da v datoteki `vizualizacija.r` za iskanje "podtabel", namesto ročnega štetja vrstic, uporabiš funkcijo `filter`, saj se bodo s tem podatki avtomatsko posodobili, če se bo spremenila prvotna tabela. Na primer 
```r
gospodarskadejavnostA_osmanj_moski <- gospodarskadejavnost %>% 
filter(izobrazba == "Osnovnošolska ali manj", spol == "Moški",
 gospodarska.dejavnost == "A KMETIJSTVO IN LOV, GOZDARSTVO, RIBIŠTVO")
```
 Izračun *najvišje in najnižje plače  v vsaki panogi glede na izobrazbo in spol*  si lahko zelo poenostaviš z uporabo funkcij `group_by` in `summarise` (posledično bo tudi koda precej krajša in bistveno bolj pregledna; izogneš se tudi ročnemu pisanju nekaterih zelo dolgih vektorjev, npr. `izobrazba`, `maksimalna_placa_moski`, ...). Za najvišje plače lahko narediš nekaj takega
```r
maksimumi <- gospodarskadejavnost %>% 
group_by(gospodarska.dejavnost, izobrazba, spol) %>% 
summarise(maksimum = max(placa))
```
S tem dobiš maksimalno plačo za vsako panogo, stopnjo izobrazbe in spol.  Dobiš tabelo, ki je v obliki  *tidy data* in je po podatkih enaka tabeli `maksimalna_minimalna` (le da vsebuje samo podatke o maksimum), ki pa ni v *tidy data*. 
Za minimum narediš podobno. Tabeli za max in min lahko nato tudi združiš (pazi le, da bo tudi skupna tabela v *tidy data*).  Za posamezen graf nato le ustrezno filtriraš to tabelo. 

Opazil sem še, da ti na grafih manjkajo legende.

**Comment by nezakrzan** [comment]
Hvala za komentar in pomoč, bom popravila
