### ISSUE TITLE
Zemljevid

### ISSUE THREAD

**Issue by katarinabrilej** [nezakrzan/APPR-2020-21#2]
Pri uvozu zemljevida moraš uporabiti kodiranje UTF-8 namesto Windows-1250, tako se bodo šumniki na grafu pravilno izpisali. Torej:
```
zemljevid_slovenije <- uvozi.zemljevid("http://biogeo.ucdavis.edu/data/gadm2.8/shp/SVN_adm_shp.zip",
                                       "SVN_adm1", mapa = "zemljevid_Slovenije", encoding = "UTF-8") %>% fortify()
```

**Comment by nezakrzan** [comment]
Hvala za pomoč, vendar še vedno nimam šumnikov

**Comment by katarinabrilej** [comment]
Tudi, če poženeš program v Binderju?

**Comment by nezakrzan** [comment]
Ja.
Zdaj je prof. Janoš Vidali poslal mail z navodili, da posodobimo kodo. Bom probala še to, potem pa verjetno bo.

**Comment by nezakrzan** [comment]
Smo razrešili težave, hvala za pomoč.
