### ISSUE TITLE
Graf1 - legenda

### ISSUE THREAD

**Issue by katarinabrilej** [nezakrzan/APPR-2020-21#3]
Pri `grafu1` je najbolje, če daš imena dejavnosti kar na y os, vendar pa recimo odtraniš začetno črko in pa malo skrajšaš imena. Lahko potem še razdeliš v dve vrstici oz. določiš maksimalno širino tega dela, kjer so izpisana imena (`str_wrap`), zato potrebuješ knjižnico `stringr`.
```
library(stringr)
ggplot(gd_sprememba1 ,aes(x=str_wrap(gd_sprememba.gospodarska.dejavnost,30), y=gd_sprememba.sprememba, fill=factor(gd_sprememba.spol))) + 
  geom_col(position="dodge")  + 
  coord_flip() +
  guides(fill=guide_legend("Spol")) +
  xlab("Gospodarska dejavnost") + 
  ylab("Sprememba")+
  ggtitle("Sprememba plače glede na gospodarsko dejavnost")
```

**Comment by nezakrzan** [comment]
Sem uredila, hvala
