### ISSUE TITLE
Napredna analiza 

### ISSUE THREAD

**Issue by nezakrzan** [nezakrzan/APPR-2020-21#6]
Pr napredni analizi  v kodi ```analiza``` sem želela narediti napoved rasti bruto minimalne plače v Sloveniji. 
Pri funkciji ```napoved``` pa mi izpiše error, ki ga ne razumem ravno najbolje in ne vem kako bi ga lahko popravila.

**Comment by timotejvesel** [comment]
S tem bi moralo delovati
```r
odstopanje <- lm(data = napoved_slo, Placa ~ as.numeric(Leto))
```

**Comment by nezakrzan** [comment]
Hvala.
Zdaj mi pri grafu ```graf_odstopanja``` izpiše error, da ne najde objekta ```Leto``` in mi ni jasno zakaj.

**Comment by jaanos** [comment]
Še bolje bo, če že pri uvozu razpredelnice `min_place` poskrbiš, da se leta pretvorijo v števila:
```R
min_place <- read_html("podatki/minimalne_place.htm") %>% html_node(xpath="//table[@class='infoData']") %>%
  html_table() %>% pivot_longer(-timegeo, names_to="Leto", values_to="Placa", names_transform=c(Leto=parse_number)) %>%
  mutate(Placa=parse_number(Placa, na=c(":", ":(z)"), locale=locale(decimal_mark=".", grouping_mark=","))) %>%
  rename(Drzava=timegeo) %>% drop_na(Placa)
```
Tukaj sem namesto `melt` uporabil funkcijo `pivot_longer`, ki služi istemu namenu, vendar je bolj robustna - tako je npr. mogoče poskrbeti za pretvorbo letnic v števila že v sami funkciji (lahko pa bi to naredila tudi v sledečem `mutate`). Tako tudi ne bo treba uvoziti knjižnic `reshape2` in `reshape` - sploh za slednjo odsvetujem uvažanje, saj zna povzročati probleme. Zgornji uvoz tudi poskrbi za ustrezno poimenovanje stolpcev, tako da do zgoraj opisanega problema ne bi smelo prihajati (morda si na novo izvedla uvoz razpredelnice `min_place`, ne pa tudi preimenovanja stolpcev).

**Comment by timotejvesel** [comment]
Kar sem napisal zgoraj, seveda ne deluje pravilno. Če narediš popravek od @jaanos, pa bo tvoja prvotna koda delovala pravilno. Si pa na grafu verjetno želela prikazati napovedi plač od leta 2016 naprej, zato moraš uporabiti 
```r
geom_point(data=napoved, aes(x=Leto, y=Placa), color='dark green', size=2)
```
namesto 

```r
geom_point(data=odstopanje, aes(x=Leto, y=Placa), color='dark green', size=2)
```

**Comment by nezakrzan** [comment]
Mislim, da sem rešila težavo. Hvala za pomoč
